/* Curated feminist reading list — organized by current, classic, and in-depth categories. */
window.POSTROE_WORKS = [
  // --- Jessica Valenti & direct inspirations ---
  { category: 'Frontline', accent: 'our', title: 'Abortion: Our Bodies, Their Lies, and the Truths We Use to Win', author: 'Jessica Valenti', year: 2024,
    blurb: 'The book that inspired this dashboard. A manifesto and field guide for the post-Dobbs era.',
    url: 'https://www.jessicavalenti.com/abortion-book' },
  { category: 'Frontline', accent: 'our', title: 'Abortion, Every Day (Newsletter)', author: 'Jessica Valenti', year: 2022,
    blurb: 'Daily synthesis of abortion news, legislation, and on-the-ground reporting.',
    url: 'https://jessica.substack.com' },
  { category: 'Frontline', accent: 'our', title: 'Sex Object: A Memoir', author: 'Jessica Valenti', year: 2016,
    blurb: 'New York Times bestselling memoir on surviving a culture that treats women as objects.',
    url: 'https://www.jessicavalenti.com/books' },
  { category: 'Frontline', accent: 'our', title: 'Full Frontal Feminism', author: 'Jessica Valenti', year: 2007,
    blurb: 'The accessible primer that made a generation of readers into feminists.',
    url: 'https://www.jessicavalenti.com/books' },

  // --- Contemporary feminism ---
  { category: 'Contemporary', accent: 'their', title: 'Shrill: Notes from a Loud Woman', author: 'Lindy West', year: 2016,
    blurb: 'Essays on fatness, feminism, and refusing to shrink. Became a Hulu series.',
    url: 'https://www.hachettebookgroup.com/titles/lindy-west/shrill/9780316348409/' },
  { category: 'Contemporary', accent: 'their', title: 'The Witches Are Coming', author: 'Lindy West', year: 2019,
    blurb: 'Cultural criticism on misogyny, climate, and the reactionary backlash of the 2010s.',
    url: 'https://www.hachettebookgroup.com/titles/lindy-west/the-witches-are-coming/9780316449908/' },
  { category: 'Contemporary', accent: 'their', title: 'Invisible Women: Data Bias in a World Designed for Men', author: 'Caroline Criado Perez', year: 2019,
    blurb: 'A data-driven indictment of the gender data gap — from crash tests to medication dosages.',
    url: 'https://carolinecriadoperez.com/book/invisible-women/' },
  { category: 'Contemporary', accent: 'their', title: 'Bad Feminist', author: 'Roxane Gay', year: 2014,
    blurb: 'Essays that redefined what it means to be a feminist without being a saint.',
    url: 'https://www.harpercollins.com/products/bad-feminist-roxane-gay' },
  { category: 'Contemporary', accent: 'their', title: 'Hood Feminism', author: 'Mikki Kendall', year: 2020,
    blurb: 'The feminist movement\'s blind spots on race, class, and the women left behind.',
    url: 'https://www.penguinrandomhouse.com/books/592596/hood-feminism-by-mikki-kendall/' },
  { category: 'Contemporary', accent: 'their', title: 'Men Explain Things to Me', author: 'Rebecca Solnit', year: 2014,
    blurb: 'The essay that gave us "mansplaining" and the anthology that expanded on it.',
    url: 'https://www.haymarketbooks.org/books/1539-men-explain-things-to-me' },
  { category: 'Contemporary', accent: 'their', title: 'Believing: Our Thirty-Year Journey to End Gender Violence', author: 'Anita Hill', year: 2021,
    blurb: 'Anita Hill\'s account of the decades since her 1991 testimony, and the work still ahead.',
    url: 'https://www.penguinrandomhouse.com/books/636836/believing-by-anita-hill/' },

  // --- Reproductive rights & justice ---
  { category: 'Reproductive Justice', accent: 'truth', title: 'Killing the Black Body', author: 'Dorothy Roberts', year: 1997,
    blurb: 'The foundational text on race, reproduction, and the meaning of liberty in America.',
    url: 'https://www.penguinrandomhouse.com/books/81860/killing-the-black-body-by-dorothy-roberts/' },
  { category: 'Reproductive Justice', accent: 'truth', title: 'Reproductive Justice: An Introduction', author: 'Loretta Ross & Rickie Solinger', year: 2017,
    blurb: 'The movement\'s defining framework, from the scholars who coined it.',
    url: 'https://www.ucpress.edu/book/9780520288201/reproductive-justice' },
  { category: 'Reproductive Justice', accent: 'truth', title: 'The Turnaway Study', author: 'Diana Greene Foster', year: 2020,
    blurb: 'Ten years of research on what happens to women denied the abortions they sought.',
    url: 'https://www.ansirh.org/research/ongoing/turnaway-study' },
  { category: 'Reproductive Justice', accent: 'truth', title: 'Undue Burden: Life and Death Decisions in Post-Roe America', author: 'Shefali Luthra', year: 2024,
    blurb: 'Reporter Shefali Luthra follows patients and providers across the post-Dobbs landscape.',
    url: 'https://www.penguinrandomhouse.com/books/712994/undue-burden-by-shefali-luthra/' },
  { category: 'Reproductive Justice', accent: 'truth', title: 'Controlling Women: What We Must Do Now to Save Reproductive Freedom', author: 'Kathryn Kolbert & Julie F. Kay', year: 2021,
    blurb: 'From the lawyer who argued Casey — a legal and strategic plan for the fight after Roe.',
    url: 'https://www.hachettebookgroup.com/titles/kathryn-kolbert/controlling-women/9780306925634/' },

  // --- Classics ---
  { category: 'Canon', accent: 'we', title: 'Sister Outsider', author: 'Audre Lorde', year: 1984,
    blurb: 'Essays and speeches from the Black lesbian feminist poet — still the most-cited text in feminist theory.',
    url: 'https://www.penguinrandomhouse.com/books/198292/sister-outsider-by-audre-lorde/' },
  { category: 'Canon', accent: 'we', title: 'Feminism Is for Everybody', author: 'bell hooks', year: 2000,
    blurb: 'A short, clear, urgent introduction to feminist politics from one of its defining voices.',
    url: 'https://www.routledge.com/Feminism-Is-for-Everybody-Passionate-Politics/hooks/p/book/9781138821620' },
  { category: 'Canon', accent: 'we', title: 'The Second Sex', author: 'Simone de Beauvoir', year: 1949,
    blurb: 'The existentialist text that named the problem: "One is not born, but rather becomes, a woman."',
    url: 'https://www.penguinrandomhouse.com/books/89961/the-second-sex-by-simone-de-beauvoir/' },
  { category: 'Canon', accent: 'we', title: 'The Feminine Mystique', author: 'Betty Friedan', year: 1963,
    blurb: 'The book that launched the second wave — and whose blind spots taught the next generation.',
    url: 'https://wwnorton.com/books/9780393346787' },
  { category: 'Canon', accent: 'we', title: 'Ain\'t I a Woman: Black Women and Feminism', author: 'bell hooks', year: 1981,
    blurb: 'The book that forced American feminism to reckon with race.',
    url: 'https://www.routledge.com/Aint-I-a-Woman-Black-Women-and-Feminism/hooks/p/book/9781138821484' },

  // --- Fiction & memoir ---
  { category: 'Fiction & Memoir', accent: 'sage', title: 'The Handmaid\'s Tale', author: 'Margaret Atwood', year: 1985,
    blurb: 'Every atrocity in Gilead was already happening somewhere when Atwood wrote it. Still true.',
    url: 'https://www.penguinrandomhouse.com/books/656267/the-handmaids-tale-by-margaret-atwood/' },
  { category: 'Fiction & Memoir', accent: 'sage', title: 'Red Clocks', author: 'Leni Zumas', year: 2018,
    blurb: 'A near-future American novel where abortion is illegal and IVF is banned. Uncannily prescient.',
    url: 'https://www.littlebrown.com/titles/leni-zumas/red-clocks/9780316434812/' },
  { category: 'Fiction & Memoir', accent: 'sage', title: 'Know My Name', author: 'Chanel Miller', year: 2019,
    blurb: 'The memoir of the woman known for years only as "Emily Doe" in the Stanford sexual-assault case.',
    url: 'https://www.penguinrandomhouse.com/books/604882/know-my-name-by-chanel-miller/' },
  { category: 'Fiction & Memoir', accent: 'sage', title: 'In the Dream House', author: 'Carmen Maria Machado', year: 2019,
    blurb: 'A memoir of queer domestic abuse that remade what a memoir can do formally.',
    url: 'https://www.graywolfpress.org/books/dream-house' }
];
